blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Don't know how to use it correctly?
    url: https://github.com/krau/SaveAny-Bot/discussions
    about: "Go to the discussion area to ask questions"
  - name: ðŸ“„ Documentation
    url: https://sabot.unv.app
    about: "View the documentation"
