blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ ä¸çŸ¥é“å¦‚ä½•æ­£ç¡®ä½¿ç”¨?
    url: https://github.com/krau/SaveAny-Bot/discussions
    about: "å‰å¾€è®¨è®ºåŒºæé—®"
  - name: ğŸ“„ æ–‡æ¡£
    url: https://sabot.unv.app
    about: "æŸ¥çœ‹æ–‡æ¡£"